name: Type conversion
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: pip3 install numpy
      - run: pip3 install pytest
      - run: pytest
